development:
  password: 23de2e01676a3539aa7339db5e2134c3
  theme_id: "78868742225"
  store: buyrvaart.myshopify.com
  directory: dist
  ignores:
  - themekit_ignores

production:
  password: 23de2e01676a3539aa7339db5e2134c3
  theme_id: "49552425041"
  store: buyrvaart.myshopify.com
  directory: dist
  ignores:
  - themekit_ignores
